# Generated by Django 5.1.1 on 2024-10-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pudra',
            name='bio',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pudra',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pudra',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='pudra',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
